### ISSUE TITLE
'make init' after clone not working

### ISSUE THREAD

**Issue by tamsky** [cloudposse/dev#2]
I've tried README steps on both OSX and linux:

Here's linux:
```
vagrant@vagrant-ubuntu-trusty-64:~$ git clone --recursive git@github.com:cloudposse/dev && cd dev
[snip]

vagrant@vagrant-ubuntu-trusty-64:~/dev$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
vagrant@vagrant-ubuntu-trusty-64:~$ cd dev

vagrant@vagrant-ubuntu-trusty-64:~/dev$ make init
make[1]: Entering directory `/home/vagrant/dev'
make[1]: *** No rule to make target `init'.  Stop.
make[1]: Leaving directory `/home/vagrant/dev'
make: *** [init] Error 2
```

I can see the rule:
```
vagrant@vagrant-ubuntu-trusty-64:~/dev$ fgrep 'init:' projects/tools/build-harness/templates/Makefile.build-harness 
init::
```

but this `makefile` doesn't appear to be `include`-ed yet.

**Comment by tamsky** [comment]
Is it possible that `make init` is actually **not** required at all since `build-harness` is already cloned into `projects/tools/build-harness/`?

**Comment by vadim-hleif** [comment]
@tamsky Yes, sure, you can just type `make readme` and it's works, tested it. 
All targets are available because of 
```
export BUILD_HARNESS_PATH ?= projects/tools/build-harness

include $(BUILD_HARNESS_PATH)/Makefile
```

**Comment by osterman** [comment]
@vadim-hleif this is not related to the readme =)

He's saying by following the steps in the `README.md` for getting started with the "dev" harness, that the submodules are not initialized.

**Comment by vadim-hleif** [comment]
@osterman, I did not write very well, it was an example. But i think all targets such as `readme` and `packages/install` works. `make init` is actually not required at all since build-harness is already cloned into projects/tools/build-harness/ and `Makefile` of it included in makefile in root of dev.  I'll double check how it works from steps in readme.
